---
- name: Scale down Kubernetes deployment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Scale down deployment
      command: /usr/local/bin/kubectl scale deployment pingpong-deployment --replicas=2
