---
- name: Scale Up Kubernetes deployment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Scale Up deployment
      command: /usr/local/bin/kubectl scale deployment pingpong-deployment --replicas=4